/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HealthResponse } from "./HealthResponse";

/**
 * @description Service health status
 */
export type HealthCheck200 = HealthResponse;

export type HealthCheckQueryResponse = HealthCheck200;

export type HealthCheckQuery = {
  Response: HealthCheck200;
  Errors: any;
};
