/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { HealthCheckQueryResponse } from "../../types/HealthCheck";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { healthCheck } from "../../clients/systemController/healthCheck";

export const healthCheckQueryKey = () => [{ url: "/health" }] as const;

export type HealthCheckQueryKey = ReturnType<typeof healthCheckQueryKey>;

export function healthCheckQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = healthCheckQueryKey();
  return queryOptions<
    HealthCheckQueryResponse,
    ResponseErrorConfig<Error>,
    HealthCheckQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return healthCheck({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * {@link /health}
 */
export function useHealthCheck<
  TData = HealthCheckQueryResponse,
  TQueryData = HealthCheckQueryResponse,
  TQueryKey extends QueryKey = HealthCheckQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        HealthCheckQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? healthCheckQueryKey();

  const query = useQuery(
    {
      ...healthCheckQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
