/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/client";
import type { HealthCheckQueryResponse } from "../../types/HealthCheck";

function getHealthCheckUrl() {
  const res = { method: "GET", url: `/health` as const };
  return res;
}

/**
 * {@link /health}
 */
export async function healthCheck(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HealthCheckQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getHealthCheckUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
